
version: '3.9' 		#Definición de la versión
services: 		#Especificación de los servicios
  redis_alone_01:	#redis stans alone
    image: redis:latest
    container_name: redis01
    ports:
      - "6379:6379"
    networks:
      - backend

  redis_insight:
    image: redis/redisinsight:latest
    container_name: redis_insight01
    ports:
      - "5540:5540"
    depends_on:
      - redis_alone_01
    networks:
      - backend

  mongo_alone:
    image: mongo
    container_name: mongo01
    ports:
      - "27017:27017"
    networks:
      - backend
  
  mongo_express:
    image: mongo-express
    container_name: mongo_express_01
    ports:
      - "8081:8081"
    depends_on:
      - mongo_alone
    networks:
      - backend

networks:
  backend:
    driver: bridge