services:
  redis_alone_01:
    image: redis:latest
    container_name: redis01
    ports:
      - "6379:6379"
    volumes:
      - ./VolumenesRedis/palRedis:/data
    networks:
      - backend

  redis_insight:
    image: redis/redisinsight:latest
    container_name: redis_insight01
    ports:
      - "5540:5540"
    depends_on:
      - redis_alone_01
    networks:
      - backend

  redis_stack:
    image: redis/redis-stack:latest
    container_name: redis_stack01
    ports:
      - "8001:8001"
    volumes:
      - ./VolumenesRedis/palStack:/data
    networks:
      - backend

  mongo_alone:
    image: mongo:latest
    container_name: mongo01
    ports:
      - "27017:27017"
    volumes:
      - ./volumenesMongo:/data
    networks:
      - backend

  mongo_compass:
    image: mongo:latest
    container_name: mongo_compass01
    ports:
      - "27018:27017"
    volumes:
      - ./volumenesMongo:/data
    networks:
      - backend

  mongo_express:
    image: mongo-express:latest
    container_name: mongo_express01
    ports:
      - "8081:8081"
    depends_on:
      - mongo_alone
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo_alone
      ME_CONFIG_BASICAUTH_USERNAME: ''
      ME_CONFIG_BASICAUTH_PASSWORD: ''
    restart: always
    networks:
      - backend
  
  Neo4j_alone01:
    image: neo4j:latest
    container_name: neo4j01
    ports:
      - "7474:7474"
      - "7867:7867"
    volumes:
      - ./volumenesNeo4j:/data
    networks:
      - backend

networks:
  backend:
    driver: bridge